name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: [main]  # o la rama principal de tu repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        run: cargo install mdbook --version 0.4.37  # ajusta si usas otra
      - name: Build the book
        run: mdbook build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
